version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: notesapp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - infosonik-network
    restart: unless-stopped

  app:
    build: .
    environment:
      DATABASE_URL: postgresql://user:${DB_PASSWORD:-password}@db:5432/notesapp
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    depends_on:
      - db
    networks:
      - infosonik-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web-app.rule=Host(`infsnk-app-01.tawfiqulbari.work`)"
      - "traefik.http.routers.web-app.entrypoints=websecure"
      - "traefik.http.routers.web-app.tls.certresolver=letsencrypt"
      - "traefik.http.services.web-app.loadbalancer.server.port=8000"

volumes:
  postgres_data:

networks:
  infosonik-network:
    external: true
