version: '3.8'

services:
  traefik:
    image: traefik:v3.0
    container_name: traefik-prod
    command:
      - "--configfile=/etc/traefik/traefik.yml"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml
      - letsencrypt:/letsencrypt
    networks:
      - app-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: webapp_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-securepassword123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  app:
    build: .
    environment:
      DATABASE_URL: postgresql://user:${DB_PASSWORD:-securepassword123}@db:5432/webapp_db
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      SECRET_KEY: ${SECRET_KEY}
      ENVIRONMENT: ${ENVIRONMENT:-production}
      DEBUG: ${DEBUG:-false}
    depends_on:
      - db
      - traefik
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
