version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: notesapp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-securepassword123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  app:
    build: .
    ports:
      - "8080:8000"
    environment:
      DATABASE_URL: postgresql://user:${DB_PASSWORD:-securepassword123}@db:5432/notesapp
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
