# Traefik v3 Static Configuration
global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true
  debug: false

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  dashboard:
    address: ":8081"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: app-network
    watch: true
  file:
    filename: /etc/traefik/dynamic/traefik-dynamic.yml
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@tawfiqulbari.work
      storage: /letsencrypt/acme.json
      tlsChallenge: {}
      keyType: EC256
      preferredChain: "ISRG Root X1"
