http:
  middlewares:
    auth:
      basicAuth:
        users:
          - "admin:$2y$05$9v3v2v1v0v9v8v7v6v5v4v3v2v1v0v9v8v7v6v5v4v3v2v1v0"  # admin:securepassword
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

  routers:
    http-to-https:
      rule: HostRegexp(`{host:.+}`)
      entryPoints:
        - web
      middlewares:
        - redirect-to-https
      service: noop@internal